# Generated by Django 5.2 on 2025-05-19 11:07

import autoslug.fields
import django.db.models.deletion
import easy_thumbnails.fields
import myshop.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ví dụ: Color, Size, Material,...', max_length=100)),
                ('slug', models.SlugField(help_text='color, size,...', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên thương hiệu.', max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='Slug của thương hiệu.', populate_from='name', unique=True)),
                ('desc', models.TextField(blank=True, help_text='Mô tả chi tiết về thương hiệu.')),
                ('desc_safe', models.TextField(blank=True, help_text='Mô tả chi tiết về thương hiệu (safe)')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Hình ảnh logo thương hiệu.', upload_to=myshop.utils.upload_product_brand_image)),
                ('order', models.IntegerField(default=0, help_text='Độ ưu tiên hiển thị. Càng lớn thì càng hiển thị trước.')),
                ('meta_title', models.CharField(blank=True, help_text='Tiêu đề SEO', max_length=60)),
                ('meta_desc', models.CharField(blank=True, help_text='Mô tả cho SEO trang, tối đa 145 ký tự. Nếu để trống thì sẽ hệ thống sẽ tự động lấy từ mô tả.', max_length=145)),
                ('admin_notes', models.TextField(blank=True, help_text='Ghi chú của quản trị viên.')),
            ],
            options={
                'verbose_name_plural': 'brands',
                'ordering': ('-order', 'name'),
                'indexes': [models.Index(fields=['-order', 'name'], name='myshop_bran_order_b24677_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên danh mục sản phẩm.', max_length=255, unique=True)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='Slug của danh mục.', populate_from='name', unique=True)),
                ('desc', models.TextField(blank=True, help_text='Mô tả chi tiết về danh mục sản phẩm.', max_length=255, null=True)),
                ('desc_safe', models.TextField(blank=True, help_text='Mô tả chi tiết về danh mục sản phẩm (safe).', max_length=255, null=True)),
                ('img', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Hình ảnh danh mục.', upload_to=myshop.utils.upload_product_category_image)),
                ('order', models.IntegerField(default=0, help_text='Thứ tự hiển thị. Lớn hơn thì hiển thị trước.')),
                ('meta_title', models.CharField(blank=True, help_text='Tiêu đề SEO', max_length=60)),
                ('meta_desc', models.CharField(blank=True, help_text='Mô tả SEO cho trang, tối đa 145 ký tự. Nếu để trống thì sẽ hệ thống sẽ tự động lấy từ mô tả.', max_length=145)),
                ('admin_notes', models.TextField(blank=True, help_text='Ghi chú của quản trị viên.')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('-order', 'name'),
                'indexes': [models.Index(fields=['-order', 'name'], name='myshop_cate_order_a7ce2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên của sản phẩm.', max_length=255, verbose_name='Tên sản phẩm')),
                ('code', models.CharField(editable=False, help_text='Mã ngẫu nhiên của sản phẩm (8 số), được tạo tự động.', max_length=8, unique=True, verbose_name='Mã sản phẩm')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='Slug của sản phẩm.', populate_from='name', unique=True)),
                ('desc', models.TextField(help_text='Mô tả chi tiết về sản phẩm.', verbose_name='Mô tả chi tiết')),
                ('desc_safe', models.TextField(blank=True, help_text='Mô tả chi tiết về sản phẩm đã loại bỏ các thẻ HTML không cần thiết.', verbose_name='Mô tả chi tiết (An toàn)')),
                ('desc_short', models.CharField(help_text='Mô tả ngắn về sản phẩm.', max_length=255, verbose_name='Mô tả ngắn')),
                ('desc_short_safe', models.CharField(blank=True, help_text='Mô tả ngắn về sản phẩm đã loại bỏ các thẻ HTML không cần thiết.', max_length=255, verbose_name='Mô tả ngắn (An toàn)')),
                ('seller_notes', models.TextField(blank=True, help_text='Ghi chú thêm của người bán về sản phẩm, không có thì để trống.', verbose_name='Ghi chú thêm của người bán')),
                ('seller_notes_safe', models.TextField(blank=True, help_text='Ghi chú thêm của người bán về sản phẩm, đã loại bỏ các thẻ HTML không cần thiết.', verbose_name='Ghi chú thêm của người bán (An toàn)')),
                ('price_origin', models.FloatField(help_text='Giá gốc của sản phẩm.', verbose_name='Giá gốc')),
                ('price_promo', models.FloatField(blank=True, help_text='Giá khuyến mãi của sản phẩm.', null=True, verbose_name='Giá khuyến mãi')),
                ('stock', models.PositiveIntegerField(help_text='Số lượng sản phẩm còn lại trong kho.', verbose_name='Tồn kho')),
                ('is_available', models.BooleanField(default=True, help_text='Tình trạng hiện có của sản phẩm (còn hàng hay hết hàng).', verbose_name='Còn hàng?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('times_purchased', models.PositiveIntegerField(default=0, help_text='Số lần sản phẩm được mua.', verbose_name='Số lần sản phẩm được mua')),
                ('admin_notes', models.TextField(blank=True, help_text='Ghi chú của quản trị viên.')),
                ('meta_title', models.CharField(blank=True, help_text='Tiêu đề SEO cho sản phẩm tối đa 60 ký tự. Nếu để trống thì sẽ hệ thống sẽ tự động lấy từ tên sản phẩm.', max_length=60)),
                ('meta_desc', models.CharField(blank=True, help_text='Mô tả SEO cho sản phẩm, tối đa 145 ký tự. Nếu để trống thì sẽ hệ thống sẽ tự động lấy từ mô tả.', max_length=145)),
                ('brand', models.ForeignKey(blank=True, help_text='Thương hiệu của sản phẩm.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_product_set', to='myshop.brand', verbose_name='Thương hiệu')),
                ('category', models.ForeignKey(blank=True, help_text='Danh mục sản phẩm, sản phẩm thuộc danh mục nào.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_product_set', to='myshop.category', verbose_name='Danh mục')),
                ('cross_sell', models.ManyToManyField(blank=True, help_text='Sản phẩm thường được mua cùng nhau, tự chọn để tối ưu hóa bán chéo (cross-sell).', to='myshop.product', verbose_name='Bán chéo')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='Ví dụ: Red, Blue, M, L, Cotton...', max_length=100)),
                ('code', models.CharField(blank=True, help_text='Mã màu sắc, mã kích thước,...', max_length=32, null=True, unique=True)),
                ('attribute', models.ForeignKey(help_text='Giá trị thuộc tính của sản phẩm, ví dụ: Màu sắc, Kích thước,...', on_delete=django.db.models.deletion.CASCADE, related_name='product_attribute_set', to='myshop.productattribute')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_variation', models.FloatField(blank=True, help_text='Giá của biến thể sản phẩm.', null=True)),
                ('attributes', models.ManyToManyField(related_name='product_variation_attributes_set', to='myshop.productattributevalue')),
                ('product', models.ForeignKey(help_text='Biến thể của sản phẩm, có thể là màu sắc, kích thước,...', on_delete=django.db.models.deletion.CASCADE, related_name='product_variation_set', to='myshop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Điểm đánh giá của sản phẩm, từ 1 đến 5 sao.')),
                ('subject', models.CharField(blank=True, help_text='Tiêu đề review', max_length=100)),
                ('content', models.TextField(blank=True, help_text='Nội dung review.')),
                ('ip_review', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=False, help_text='Trạng thái đánh giá, True: Đã duyệt, False: Chưa duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo đánh giá.')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian cập nhật đánh giá.')),
                ('admin_notes', models.TextField(blank=True, help_text='Ghi chú của quản trị viên.')),
                ('product', models.ForeignKey(help_text='Sản phẩm được đánh giá.', on_delete=django.db.models.deletion.CASCADE, related_name='product_review_set', to='myshop.product')),
                ('profile', models.ForeignKey(help_text='Người dùng đánh giá.', on_delete=django.db.models.deletion.CASCADE, related_name='profile_review_set', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên tags.', max_length=255, unique=True)),
                ('desc', models.TextField(blank=True, help_text='Mô tả chi tiết về tags.')),
                ('desc_safe', models.TextField(blank=True, help_text='Mô tả chi tiết về tags (safe).')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='Slug của tags.', populate_from='name', unique=True)),
                ('meta_title', models.CharField(blank=True, help_text='Tiêu đề SEO', max_length=60)),
                ('meta_desc', models.CharField(blank=True, help_text='Mô tả cho SEO trang, tối đa 145 ký tự. Nếu để trống thì sẽ hệ thống sẽ tự động lấy từ mô tả.', max_length=145)),
                ('admin_notes', models.TextField(blank=True, help_text='Ghi chú của quản trị viên.')),
            ],
            options={
                'verbose_name_plural': 'tags',
                'indexes': [models.Index(fields=['name'], name='myshop_tag_name_388bb2_idx')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Tags của sản phẩm, giúp tìm kiếm sản phẩm dễ dàng hơn, được chọn nhiều tags.', related_name='tags_product_set', to='myshop.tag', verbose_name='Thẻ tags sản phẩm'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, help_text='Chữ thay thế cho hình ảnh', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('img', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Hình ảnh sản phẩm.', upload_to=myshop.utils.upload_product_image)),
                ('order', models.IntegerField(default=0, help_text='Thứ tự hiển thị hình ảnh. Càng lớn thì càng hiển thị trước.')),
                ('removed', models.BooleanField(default=False, help_text='Đánh dấu hình ảnh đã bị xóa hay chưa.')),
                ('product', models.ForeignKey(blank=True, help_text='Hình ảnh của sản phẩm.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images_set', to='myshop.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product', 'order', 'removed'], name='myshop_prod_product_da14af_idx')],
            },
        ),
    ]
