# Generated by Django 5.2 on 2025-05-23 08:23

import django.db.models.deletion
import easy_thumbnails.fields
import myshop.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên màu sắc sản phẩm', max_length=100, verbose_name='Tên màu')),
                ('value', models.CharField(help_text='Giá trị dùng làm id (vd: color-black)', max_length=50, verbose_name='Giá trị')),
                ('color_code', models.CharField(blank=True, help_text='Mã màu sắc (hex code, vd: #FFFFFF)', max_length=10, verbose_name='Mã màu')),
            ],
            options={
                'verbose_name': 'Màu sắc sản phẩm',
                'verbose_name_plural': 'Màu sắc sản phẩm',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên kích thước sản phẩm', max_length=10, verbose_name='Tên kích thước')),
                ('value', models.CharField(help_text='Giá trị dùng làm id (vd: size-xl)', max_length=20, verbose_name='Giá trị')),
                ('order', models.PositiveIntegerField(default=0, help_text='Thứ tự sắp xếp', verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Kích thước sản phẩm',
                'verbose_name_plural': 'Kích thước sản phẩm',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductColorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(help_text='Chữ thay thế cho hình ảnh', max_length=255)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to=myshop.utils.upload_product_image, verbose_name='Hình ảnh')),
                ('order', models.PositiveIntegerField(default=0, help_text='Thứ tự hiển thị', verbose_name='Thứ tự')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_images_set', to='myshop.productcolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color_images_set', to='myshop.product')),
            ],
            options={
                'verbose_name': 'Ảnh màu sắc sản phẩm',
                'verbose_name_plural': 'Ảnh màu sắc sản phẩm',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, help_text='Mã SKU riêng cho biến thể này, được tạo tự động.', max_length=13, unique=True, verbose_name='Mã SKU')),
                ('price_origin', models.FloatField(blank=True, help_text='Giá của biến thể', null=True, verbose_name='Giá của biến thể')),
                ('price_promo', models.FloatField(blank=True, help_text='Giá khuyến mãi của biến thể', null=True, verbose_name='Giá khuyến mãi của biến thể')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants_color_set', to='myshop.productcolor', verbose_name='Màu sắc')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants_product_set', to='myshop.product', verbose_name='Sản phẩm')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants_size_set', to='myshop.productsize', verbose_name='Kích thước')),
            ],
            options={
                'verbose_name': 'Biến thể sản phẩm',
                'verbose_name_plural': 'Biến thể sản phẩm',
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
