# Generated by Django 5.2 on 2025-05-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_productcolor_productsize_productcolorimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='code',
            field=models.CharField(blank=True, unique=True, editable=False, help_text='Mã đánh giá sản phẩm, được tạo tự động.', max_length=13),
        ),
        migrations.AddField(
            model_name='review',
            name='content_safe',
            field=models.TextField(blank=True, help_text='Nội dung review (safe).'),
        ),
    ]
