# Generated by Django 5.2 on 2025-05-27 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_review_code_review_content_safe'),
        ('profiles', '0002_remove_profile_phone_remove_shipping_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='profile',
            field=models.ForeignKey(blank=True, help_text='Người dùng đánh giá.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_review_set', to='profiles.profile'),
        ),
    ]
