# Generated by Django 5.2 on 2025-05-27 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0004_alter_review_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('removed', models.BooleanField(default=False, help_text='Đánh dấu sản phẩm đã bị xóa khỏi danh sách yêu thích hay chưa.')),
                ('product', models.ForeignKey(help_text='Sản phẩm được người dùng thích.', on_delete=django.db.models.deletion.CASCADE, related_name='product_wishlist_set', to='myshop.product')),
                ('user', models.ForeignKey(help_text='Người dùng thích sản phẩm.', on_delete=django.db.models.deletion.CASCADE, related_name='user_wishlist_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'removed', '-created_at'], name='myshop_wish_user_id_c6805d_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('removed', False)), fields=('user', 'product'), name='unique_wishlist_2206')],
            },
        ),
    ]
