# Generated by Django 5.2 on 2025-05-30 09:17

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_wishlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên thuế, ví dụ: Standard Tax, Los Angeles Tax, Texas Tax.', max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text='Mã định danh cho thuế.', max_length=13, unique=True)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, help_text='Giá trị thuế áp dụng cho đơn hàng.', max_digits=9)),
                ('admin_notes', models.TextField(blank=True, help_text='Ghi chú của quản trị viên về thuế.')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên phí vận chuyển, ví dụ: Standard Shipping, Express Shipping.', max_length=100, unique=True)),
                ('code', models.CharField(blank=True, help_text='Mã định danh cho phí vận chuyển.', max_length=13, unique=True)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, help_text='Giá trị phí vận chuyển.', max_digits=9)),
                ('admin_notes', models.TextField(blank=True, help_text='Ghi chú của quản trị viên về phí vận chuyển.')),
            ],
        ),
        migrations.RemoveField(
            model_name='productattributevalue',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='product',
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Session key cho khách chưa đăng nhập', max_length=40, null=True)),
                ('quantity', models.IntegerField(default=1, help_text='Số lượng sản phẩm trong giỏ hàng.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed', models.BooleanField(default=False)),
                ('product', models.ForeignKey(help_text='Sản phẩm trong giỏ hàng.', on_delete=django.db.models.deletion.CASCADE, related_name='product_cart_item_set', to='myshop.product')),
                ('user', models.ForeignKey(blank=True, help_text='Người mua', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_cart_item_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, help_text='Mã đơn hàng, được tạo tự động.', max_length=13, unique=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, help_text='Tổng tiền hàng trước thuế và phí vận chuyển', max_digits=9)),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, help_text='Tổng số tiền của đơn hàng, bao gồm tiền hàng, thuế và phí vận chuyển', max_digits=9)),
                ('payment_method', models.CharField(choices=[('PP', 'PayPal')], db_index=True, default='PP', max_length=2)),
                ('status', models.CharField(choices=[('W', 'Đang chờ xử lý'), ('C', 'Đã xác nhận'), ('S', 'Đang giao hàng'), ('F', 'Đã hoàn thành'), ('R', 'Đã hủy'), ('X', 'Đang tranh chấp')], db_index=True, default='W', help_text='Trạng thái của đơn hàng.', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('success_confirmed', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('first_name', models.CharField(help_text='Tên của người nhận hàng', max_length=255, verbose_name='Tên')),
                ('last_name', models.CharField(help_text='Họ của người nhận hàng', max_length=255, verbose_name='Họ')),
                ('email', models.EmailField(help_text='Địa chỉ Email của người nhận hàng', max_length=254, verbose_name='Email')),
                ('street', models.CharField(help_text='Địa chỉ của người nhận hàng, gồm số nhà và tên đường,...', max_length=255, verbose_name='Địa chỉ cụ thể')),
                ('state', models.CharField(blank=True, help_text='Tên quận huyện người nhận hàng đang sống', max_length=255, null=True, verbose_name='Quận / Huyện')),
                ('city', models.CharField(blank=True, help_text='Tên thành phố, thị xã người nhận hàng đang sống', max_length=255, verbose_name='Thành Phố / Thị Xã')),
                ('country', models.CharField(help_text='Quốc gia người nhận hàng đang sống', verbose_name=django_countries.fields.CountryField(max_length=2))),
                ('zip_code', models.CharField(help_text='Mã bưu chính', max_length=10)),
                ('admin_notes', models.TextField(blank=True, help_text='Ghi chú của quản trị viên.')),
                ('user', models.ForeignKey(blank=True, help_text='Người dùng đã đặt hàng, có thể là thành viên hoặc khách vãng lai.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_order_set', to=settings.AUTH_USER_MODEL)),
                ('order_tax', models.ForeignKey(blank=True, help_text='Thuế áp dụng cho đơn hàng.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_tax_set', to='myshop.ordertax')),
                ('shipping_fee', models.ForeignKey(blank=True, help_text='Phí vận chuyển áp dụng cho đơn hàng.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_fee_set', to='myshop.shippingfee')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Số lượng sản phẩm trong đơn hàng.')),
                ('price', models.DecimalField(decimal_places=0, default=0, help_text='Giá bán của sản phẩm tại thời điểm đặt hàng.', max_digits=9)),
                ('order', models.ForeignKey(help_text='Đơn hàng mà sản phẩm này thuộc về.', on_delete=django.db.models.deletion.CASCADE, related_name='order_items_set', to='myshop.order')),
                ('product', models.ForeignKey(help_text='Sản phẩm trong đơn hàng.', on_delete=django.db.models.deletion.CASCADE, related_name='product_order_items_set', to='myshop.product')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='ProductAttributeValue',
        ),
        migrations.DeleteModel(
            name='ProductVariation',
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['user', 'removed', '-updated_at'], name='myshop_cart_user_id_4fcb8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'product'), name='unique_user_product_2206'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('session_key', 'product'), name='unique_session_product_2206'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='myshop_orde_user_id_f20e59_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status', '-created_at'], name='myshop_orde_user_id_dd78d4_idx'),
        ),
    ]
