# Generated by Django 5.2 on 2025-05-31 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0006_ordertax_shippingfee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_user_product_2206',
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_session_product_2206',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant_product',
            field=models.ForeignKey(blank=True, help_text='Sản phẩm trong giỏ hàng.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_cart_item_set', to='myshop.productvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_product',
            field=models.ForeignKey(blank=True, help_text='Sản phẩm trong đơn hàng.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_order_items_set', to='myshop.productvariant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(help_text='Quốc gia người nhận hàng đang sống', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('user', 'variant_product'), name='unique_user_product_2206'),
        ),
    ]
