# Generated by Django 5.2 on 2025-05-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0007_remove_cartitem_unique_user_product_2206_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='session_key',
            field=models.CharField(blank=True, help_text='Khóa phiên của người dùng, dùng để xác định giỏ hàng của người dùng chưa đăng nhập.', max_length=40, null=True),
        ),
    ]
