# Generated by Django 5.2 on 2025-05-14 07:38

import django.db.models.deletion
import easy_thumbnails.fields
import utils.function
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tiêu đề slider', max_length=100)),
                ('desc', models.TextField(blank=True, help_text='Mô tả slider')),
                ('desc_safe', models.TextField(blank=True, help_text='Mô tả an toàn')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(help_text='Ảnh đại diện slider', upload_to=utils.function.upload_home_slider_image)),
                ('link', models.CharField(blank=True, help_text='Liên kết đến bài viết hoặc trang khác.', max_length=200)),
                ('button_text', models.CharField(blank=True, help_text='Tiêu đề nút bấm chứa link.', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Thứ tự hiển thị')),
                ('status', models.BooleanField(default=True, help_text='Trạng thái hiển thị')),
            ],
            options={
                'verbose_name': 'Slider trang chủ',
                'verbose_name_plural': 'Slider trang chủ',
                'ordering': ('-order',),
            },
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên menu', max_length=100)),
                ('link', models.URLField(blank=True, help_text='Liên kết đến bài viết hoặc trang khác.')),
                ('target', models.CharField(blank=True, default='_self', help_text='Target của liên kết (ví dụ: _blank, _self, _parent, _top)', max_length=20)),
                ('rel', models.CharField(blank=True, default='noopener noreferrer', help_text='Thuộc tính rel của liên kết (ví dụ: noopener noreferrer nofollow)', max_length=200)),
                ('order', models.PositiveIntegerField(default=1, help_text='Thứ tự hiển thị')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubMenuGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên nhóm menu', max_length=100)),
                ('order', models.PositiveIntegerField(default=1, help_text='Thứ tự hiển thị')),
                ('main_menu', models.ForeignKey(help_text='Menu cấp 1', on_delete=django.db.models.deletion.CASCADE, related_name='menu_groups_set', to='utils.mainmenu')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên item menu', max_length=100)),
                ('link', models.URLField(blank=True, help_text='Liên kết đến bài viết hoặc trang khác.')),
                ('target', models.CharField(blank=True, default='_self', help_text='Target của liên kết (ví dụ: _blank, _self, _parent, _top)', max_length=20)),
                ('rel', models.CharField(blank=True, default='noopener noreferrer', help_text='Thuộc tính rel của liên kết (ví dụ: noopener noreferrer nofollow)', max_length=200)),
                ('order', models.PositiveIntegerField(default=1, help_text='Thứ tự hiển thị')),
                ('group', models.ForeignKey(help_text='Nhóm menu', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items_set', to='utils.submenugroup')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
