# Generated by Django 5.2 on 2025-05-27 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterMenuGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tên nhóm menu', max_length=100)),
                ('order', models.PositiveIntegerField(default=1, help_text='Thứ tự hiển thị')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Tên mục menu', max_length=100)),
                ('link', models.URLField(blank=True, help_text='Liên kết đến bài viết hoặc trang khác.')),
                ('order', models.PositiveIntegerField(default=1, help_text='Thứ tự hiển thị')),
                ('target', models.CharField(blank=True, default='_self', help_text='Target của liên kết (ví dụ: _blank, _self, _parent, _top)', max_length=20)),
                ('rel', models.CharField(blank=True, default='noopener noreferrer', help_text='Thuộc tính rel của liên kết (ví dụ: noopener noreferrer nofollow)', max_length=200)),
                ('group', models.ForeignKey(help_text='Nhóm menu chân trang', on_delete=django.db.models.deletion.CASCADE, related_name='footer_menu_items', to='utils.footermenugroup')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
