# Generated by Django 5.2 on 2025-05-27 18:46

import autoslug.fields
import easy_thumbnails.fields
import utils.function
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_footermenugroup_footermenuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nhập tiêu đề trang, tốt nhất không quá 65 ký tự', max_length=100, verbose_name='Tên trang')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='Nhập slug cho trang, sẽ tự động tạo từ tiêu đề nếu để trống', max_length=255, populate_from='title', unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(blank=True, help_text='Trích dẫn ngắn cho trang', verbose_name='Trích dẫn ngắn')),
                ('excerpt_safe', models.TextField(blank=True, help_text='Trích dẫn an toàn cho trang, đã loại bỏ HTML không an toàn', verbose_name='Trích dẫn an toàn')),
                ('content', models.TextField(help_text='Nhập nội dung cho trang', verbose_name='Nội dung')),
                ('content_safe', models.TextField(blank=True, help_text='Nội dung an toàn cho trang, đã loại bỏ HTML không an toàn', verbose_name='Nội dung an toàn')),
                ('status', models.CharField(choices=[('W', 'Nháp...'), ('P', 'Đã công khai.')], default='W', help_text='Trạng thái trang', max_length=1, verbose_name='Trạng thái')),
                ('meta_title', models.CharField(blank=True, help_text='Tiêu đề SEO cho trang, tốt nhất không quá 60 ký tự', max_length=60, verbose_name='Tiêu đề SEO')),
                ('meta_desc', models.CharField(blank=True, help_text='Mô tả SEO cho trang, tốt nhất không quá 145 ký tự', max_length=145, verbose_name='Mô tả SEO')),
                ('meta_image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Ảnh đại diện cho trang khi chia sẻ trên mạng xã hội', upload_to=utils.function.upload_static_page_image, verbose_name='Ảnh đại diện SEO')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Ngày tạo trang', verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Ngày cập nhật trang', verbose_name='Ngày cập nhật')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
