# Generated by Django 5.2

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_staticpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Nhập nội dung cho trang', verbose_name='Nội dung'),
        ),
    ]
