# Generated by Django 5.2 on 2025-05-14 07:12

import articles.utils
import autoslug.fields
import django.db.models.deletion
import easy_thumbnails.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên danh mục', max_length=100)),
                ('desc', models.TextField(blank=True, help_text='Mô tả danh mục')),
                ('desc_safe', models.TextField(blank=True, help_text='Mô tả an toàn')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='Đường dẫn thân thiện', populate_from='name', unique=True)),
                ('order', models.IntegerField(default=0, help_text='Thứ tự hiển thị')),
                ('admin_note', models.TextField(blank=True, help_text='Ghi chú của quản trị viên')),
                ('meta_title', models.CharField(blank=True, help_text='Tiêu đề SEO', max_length=60)),
                ('meta_desc', models.CharField(blank=True, help_text='Mô tả SEO', max_length=145)),
            ],
            options={
                'verbose_name': 'Danh mục bài viết',
                'verbose_name_plural': 'Danh mục bài viết',
                'ordering': ('-order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên thẻ', max_length=100)),
                ('desc', models.TextField(blank=True, help_text='Mô tả thẻ')),
                ('desc_safe', models.TextField(blank=True, help_text='Mô tả an toàn')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='Đường dẫn thân thiện', populate_from='name', unique=True)),
                ('order', models.IntegerField(default=0, help_text='Thứ tự hiển thị')),
                ('admin_note', models.TextField(blank=True, help_text='Ghi chú của quản trị viên')),
                ('meta_title', models.CharField(blank=True, help_text='Tiêu đề SEO', max_length=60)),
                ('meta_desc', models.CharField(blank=True, help_text='Mô tả SEO', max_length=145)),
            ],
            options={
                'verbose_name': 'Thẻ bài viết',
                'verbose_name_plural': 'Thẻ bài viết',
                'ordering': ('-order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Tiêu đề bài viết', max_length=100)),
                ('code', models.CharField(blank=True, help_text='Mã bài viết. Tự động tạo khi tạo mới', max_length=13, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Trích dẫn bài viết')),
                ('excerpt_safe', models.TextField(blank=True, help_text='Trích dẫn bài viết (safe)')),
                ('featured_image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Ảnh đại diện bài viết', upload_to=articles.utils.upload_articles_image)),
                ('content', models.TextField(blank=True, help_text='Nội dung bài viết')),
                ('content_safe', models.TextField(blank=True, help_text='Nội dung bài viết (safe)')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, help_text='Đường dẫn thân thiện', populate_from='title', unique=True)),
                ('author_name', models.CharField(blank=True, help_text='Tên tác giả (nếu không phải là người dùng)', max_length=100)),
                ('published_at', models.DateTimeField(blank=True, help_text='Ngày xuất bản', null=True)),
                ('num_views', models.IntegerField(default=0, help_text='Số lượt xem')),
                ('featured', models.BooleanField(default=False, help_text='Bài viết nổi bật')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('published', 'Đã xuất bản'), ('private', 'Riêng tư'), ('archived', 'Đã lưu trữ'), ('deleted', 'Đã xóa')], default='draft', help_text='Trạng thái bài viết', max_length=20)),
                ('meta_title', models.CharField(blank=True, help_text='Tiêu đề SEO', max_length=60)),
                ('meta_desc', models.CharField(blank=True, help_text='Mô tả SEO', max_length=145)),
                ('meta_image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=articles.utils.upload_articles_image)),
                ('admin_notes', models.TextField(blank=True, help_text='Ghi chú của admin')),
                ('admin_check', models.DateTimeField(blank=True, help_text='Ngày kiểm tra của admin', null=True)),
                ('author', models.ForeignKey(blank=True, help_text='Tác giả bài viết', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_author_set', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, default=1, help_text='Danh mục bài viết', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_set', to='articles.articlecategory')),
                ('tags', models.ManyToManyField(blank=True, help_text='Thẻ bài viết', related_name='tags_set', to='articles.articletag')),
            ],
            options={
                'verbose_name': 'Bài viết',
                'verbose_name_plural': 'Bài viết',
                'ordering': ('-published_at',),
            },
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Mã bình luận. Tự động tạo khi tạo mới', max_length=13, unique=True)),
                ('content', models.TextField(help_text='Nội dung bình luận')),
                ('content_safe', models.TextField(help_text='Nội dung bình luận (safe)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Ngày tạo bình luận')),
                ('removed', models.BooleanField(default=False, help_text='Đã xóa')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Ngày cập nhật bình luận')),
                ('article', models.ForeignKey(help_text='Bài viết', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.article')),
                ('author', models.ForeignKey(blank=True, help_text='Tác giả bình luận', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_comments_author_set', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Trả lời bình luận', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='articles.articlecomment')),
            ],
            options={
                'verbose_name': 'Bình luận bài viết',
                'verbose_name_plural': 'Bình luận bài viết',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('frame', models.CharField(choices=[('M', 'Tháng'), ('W', 'Tuần')], help_text='Khung thời gian', max_length=20)),
                ('num_views', models.IntegerField(default=0)),
                ('article', models.ForeignKey(help_text='Dự án', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.article')),
            ],
            options={
                'verbose_name': 'Timeline',
                'verbose_name_plural': 'Timelines',
                'indexes': [models.Index(fields=['article', 'start_date', 'frame'], name='articles_ti_article_d01bb0_idx')],
                'constraints': [models.UniqueConstraint(fields=('article', 'start_date', 'frame'), name='unique_article_timeline_14052025')],
            },
        ),
    ]
