# Generated by Django 5.2 on 2025-06-02 17:35

import autoslug.fields
import django.db.models.deletion
import easy_thumbnails.fields
import pod_shop.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.TextField(blank=True, help_text='HTML for SEO')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='name', unique=True)),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Hình ảnh logo thương hiệu.', upload_to=pod_shop.utils.upload_product_brand_image)),
                ('order', models.PositiveIntegerField(default=1, help_text='Thứ tự hiển thị thương hiệu trong danh sách, từ nhỏ đến lớn.')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.TextField(blank=True, help_text='HTML for SEO')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='name', unique=True)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Hình ảnh đại diện cho danh mục sản phẩm.', upload_to=pod_shop.utils.upload_product_category_image)),
                ('order', models.PositiveIntegerField(default=1, help_text='Thứ tự hiển thị danh mục trong danh sách, từ nhỏ đến lớn.')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('desc', models.TextField(blank=True, help_text='HTML for SEO')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Mã đơn hàng, ví dụ: "ORDER12345678"', max_length=20, unique=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, help_text='Tổng tiền hàng trước thuế và phí vận chuyển', max_digits=9)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=0, help_text='Phí vận chuyển cho đơn hàng', max_digits=9)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tổng số tiền của đơn hàng, bao gồm tiền hàng, thuế và phí vận chuyển', max_digits=9)),
                ('status', models.CharField(choices=[('W', 'Đang chờ xử lý'), ('C', 'Đã xác nhận'), ('S', 'Đang giao hàng'), ('F', 'Đã hoàn thành'), ('R', 'Đã hủy'), ('X', 'Đang tranh chấp')], db_index=True, default='W', help_text='Trạng thái của đơn hàng.', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(help_text='Tên của người nhận hàng', max_length=255, verbose_name='Tên')),
                ('last_name', models.CharField(help_text='Họ của người nhận hàng', max_length=255, verbose_name='Họ')),
                ('email', models.EmailField(help_text='Địa chỉ Email của người nhận hàng', max_length=254, verbose_name='Email')),
                ('street', models.CharField(help_text='Địa chỉ của người nhận hàng, gồm số nhà và tên đường,...', max_length=255, verbose_name='Địa chỉ cụ thể')),
                ('state', models.CharField(blank=True, help_text='Tên quận huyện người nhận hàng đang sống', max_length=255, null=True, verbose_name='Quận / Huyện')),
                ('city', models.CharField(blank=True, help_text='Tên thành phố, thị xã người nhận hàng đang sống', max_length=255, verbose_name='Thành Phố / Thị Xã')),
                ('country', models.CharField(help_text='Quốc gia người nhận hàng đang sống', max_length=100)),
                ('zip_code', models.CharField(help_text='Mã bưu chính', max_length=10)),
                ('admin_notes', models.TextField(blank=True, help_text='Ghi chú của quản trị viên.')),
                ('user', models.ForeignKey(blank=True, help_text='Người dùng đã đặt hàng (nếu có, nếu không thì là khách vãng lai)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Mã sản phẩm, ví dụ: "P1234567"', max_length=8, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='name', unique=True)),
                ('desc', models.TextField(blank=True, help_text='HTML for SEO')),
                ('desc_short', models.TextField(blank=True, help_text='Mô tả ngắn gọn về sản phẩm')),
                ('status', models.CharField(choices=[('D', 'Nháp'), ('A', 'Đang Bán'), ('O', 'Hết Hàng')], db_index=True, default='D', max_length=1)),
                ('fake_price', models.DecimalField(blank=True, decimal_places=2, help_text='Giá gạch', max_digits=10, null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Giá bán', max_digits=10)),
                ('standard_shipping_fee', models.DecimalField(decimal_places=2, default=4.95, help_text='Phí vận chuyển tiêu chuẩn cho sản phẩm này', max_digits=10)),
                ('fast_shipping_fee', models.DecimalField(decimal_places=2, default=12.95, help_text='Phí vận chuyển nhanh cho sản phẩm này', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo sản phẩm')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật sản phẩm')),
                ('best_seller', models.BooleanField(default=False, help_text='Đánh dấu sản phẩm là bán chạy nhất')),
                ('is_featured', models.BooleanField(default=False, help_text='Đánh dấu sản phẩm là nổi bật')),
                ('times_purchased', models.PositiveIntegerField(blank=True, default=0, help_text='Số lần sản phẩm được mua.', null=True, verbose_name='Số lần sản phẩm được mua')),
                ('meta_title', models.CharField(blank=True, help_text='Tiêu đề SEO cho sản phẩm tối đa 60 ký tự. Nếu để trống thì sẽ hệ thống sẽ tự động lấy từ tên sản phẩm.', max_length=60)),
                ('meta_desc', models.CharField(blank=True, help_text='Mô tả SEO cho sản phẩm, tối đa 145 ký tự. Nếu để trống thì sẽ hệ thống sẽ tự động lấy từ mô tả.', max_length=145)),
                ('admin_notes', models.TextField(blank=True, help_text='Ghi chú của quản trị viên.')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pod_shop.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_products', to='pod_shop.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='tag_products', to='pod_shop.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tên thuộc tính, ví dụ: "Size", "Color", "Gender", "Material", "Choose Your Style",...', max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='pod_shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttrItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Tên hiển thị của giá trị thuộc tính, ví dụ: "XL", "Red Devil", "Blue Sky"...', max_length=100)),
                ('value', autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='label', unique_with=('product', 'attr'))),
                ('extra', models.CharField(blank=True, help_text='Thông tin bổ sung, ví dụ: mã màu', max_length=200)),
                ('attr_order', models.PositiveIntegerField(default=0, help_text='Thứ tự hiển thị của thuộc tính trong danh sách, từ nhỏ đến lớn.')),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pod_shop.productattr')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pod_shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, help_text='Giá của sản phẩm tại thời điểm đặt hàng', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo sản phẩm trong đơn hàng')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật sản phẩm trong đơn hàng')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pod_shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='pod_shop.product')),
                ('attr_item', models.ForeignKey(blank=True, help_text='Thuộc tính sản phẩm đã chọn (nếu có)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pod_shop.productattritem')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customer_note', models.CharField(blank=True, help_text='Ghi chú của khách hàng về sản phẩm khi mua')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lớn hơn thì lên trước trong giỏ hàng')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo giỏ hàng')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật giỏ hàng')),
                ('removed', models.BooleanField(default=False, help_text='Đánh dấu sản phẩm đã bị xóa khỏi giỏ hàng')),
                ('user', models.ForeignKey(blank=True, help_text='Người dùng sở hữu giỏ hàng (nếu có, nếu không thì là khách vãng lai)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='pod_shop.product')),
                ('attr_item', models.ForeignKey(blank=True, help_text='Thuộc tính sản phẩm đã chọn (nếu có)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pod_shop.productattritem')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=pod_shop.utils.upload_product_image)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('removed', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pod_shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(help_text='Điểm đánh giá của sản phẩm, từ 1 đến 5 sao.')),
                ('subject', models.CharField(blank=True, help_text='Tiêu đề review', max_length=100)),
                ('content', models.TextField(blank=True, help_text='Nội dung review.')),
                ('content_safe', models.TextField(blank=True, help_text='Nội dung review (safe).')),
                ('ip_review', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=False, help_text='Trạng thái đánh giá, True: Đã duyệt, False: Chưa duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian tạo đánh giá.')),
                ('updated_at', models.DateTimeField(auto_now_add=True, help_text='Thời gian cập nhật đánh giá.')),
                ('admin_notes', models.TextField(blank=True, help_text='Ghi chú của quản trị viên.')),
                ('product', models.ForeignKey(help_text='Sản phẩm được đánh giá.', on_delete=django.db.models.deletion.CASCADE, related_name='product_review_set', to='pod_shop.product')),
                ('user', models.ForeignKey(blank=True, help_text='Người dùng đánh giá.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_review_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('removed', models.BooleanField(default=False, help_text='Đánh dấu sản phẩm đã bị xóa khỏi danh sách yêu thích hay chưa.')),
                ('product', models.ForeignKey(help_text='Sản phẩm được người dùng thích.', on_delete=django.db.models.deletion.CASCADE, related_name='product_wishlists', to='pod_shop.product')),
                ('user', models.ForeignKey(help_text='Người dùng thích sản phẩm.', on_delete=django.db.models.deletion.CASCADE, related_name='user_wishlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
