# Generated by Django 5.2 on 2025-06-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='attr_item',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='attr_items',
            field=models.ManyToManyField(blank=True, help_text='Thuộc tính sản phẩm đã chọn (nếu có)', related_name='+', to='pod_shop.productattritem'),
        ),
    ]
