# Generated by Django 5.2 on 2025-06-03 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_shop', '0002_remove_cartitem_attr_item_cartitem_attr_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattritem',
            name='attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attr_items', to='pod_shop.productattr'),
        ),
    ]
