# Generated by Django 5.2 on 2025-06-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_shop', '0003_alter_productattritem_attr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='attr_item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='attr_item',
            field=models.ManyToManyField(blank=True, help_text='Thuộc tính sản phẩm đã chọn (nếu có)', related_name='attr_order_items', to='pod_shop.productattritem'),
        ),
    ]
