# Generated by Django 5.2 on 2025-06-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_shop', '0004_remove_orderitem_attr_item_orderitem_attr_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='customer_note',
            field=models.TextField(blank=True, help_text='Ghi chú của khách hàng cho sản phẩm', null=True),
        ),
    ]
