# Generated by Django 5.2 on 2025-07-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_shop', '0005_orderitem_customer_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='session_key',
            field=models.CharField(blank=True, help_text='Session key của người dùng không đăng nhập', max_length=64, null=True),
        ),
    ]
