# Generated by Django 5.2 on 2025-07-04 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pod_shop', '0006_cartitem_session_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='session_key',
        ),
    ]
