# Generated by Django 5.2 on 2026-03-27 02:46

import django.db.models.deletion
import pod_shop.utils
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pod_shop', '0010_bulkreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the color', max_length=100, verbose_name='Color Name')),
                ('value', models.CharField(help_text='Value used as id (e.g. color-black)', max_length=50, verbose_name='Value')),
                ('color_code', models.CharField(blank=True, help_text='Color code (hex, e.g. #FFFFFF)', max_length=10, verbose_name='Color Code')),
            ],
            options={
                'verbose_name': 'Product Color',
                'verbose_name_plural': 'Product Colors',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the size', max_length=10, verbose_name='Size Name')),
                ('value', models.CharField(help_text='Value used as id (e.g. size-xl)', max_length=20, verbose_name='Value')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Product Size',
                'verbose_name_plural': 'Product Sizes',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='available_attrs',
            field=models.ManyToManyField(blank=True, help_text='Các thuộc tính áp dụng cho sản phẩm này (ví dụ: Size, Color, Type, ...).', related_name='products_using', to='pod_shop.productattr'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Hình ảnh logo thương hiệu.', upload_to=pod_shop.utils.upload_product_brand_image),
        ),
        migrations.AlterField(
            model_name='bulkreview',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Số lượng review sẽ được tạo với tên ngẫu nhiên.'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='Hình ảnh đại diện cho danh mục sản phẩm.', upload_to=pod_shop.utils.upload_product_category_image),
        ),
        migrations.AlterField(
            model_name='productattr',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='pod_shop.product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, upload_to=pod_shop.utils.upload_product_image),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(blank=True, help_text='Tên người đánh giá (bắt buộc nếu không đăng nhập)', max_length=255),
        ),
        migrations.CreateModel(
            name='ProductColorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(help_text='Alt text for the image', max_length=255)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to=pod_shop.utils.upload_product_image, verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order', verbose_name='Order')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_images_set', to='pod_shop.productcolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color_images_set', to='pod_shop.product')),
            ],
            options={
                'verbose_name': 'Product Color Image',
                'verbose_name_plural': 'Product Color Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, help_text='SKU for this variant. Auto-generated.', max_length=128, unique=True, verbose_name='SKU')),
                ('price_origin', models.FloatField(blank=True, help_text='Original price of the variant', null=True, verbose_name='Variant Price')),
                ('price_promo', models.FloatField(blank=True, help_text='Promo price of the variant', null=True, verbose_name='Variant Promo Price')),
                ('attr_items', models.ManyToManyField(blank=True, help_text='Các giá trị thuộc tính của biến thể', to='pod_shop.productattritem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants_product_set', to='pod_shop.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Selected product variant (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='pod_shop.productvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Selected product variant (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='pod_shop.productvariant'),
        ),
    ]
