# Generated by Django 5.2 on 2025-05-11 08:26

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Mã thành viên', max_length=13, unique=True)),
                ('first_name', models.CharField(blank=True, help_text='Tên người dùng', max_length=255, verbose_name='Tên')),
                ('last_name', models.CharField(blank=True, help_text='Họ người dùng', max_length=255, verbose_name='Họ')),
                ('email', models.EmailField(help_text='Email người dùng', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Số điện thoại của người dùng', max_length=30, verbose_name='Số điện thoại')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='Dữ liệu mở rộng')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Ghi chú của quản trị viên')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ua', models.CharField(blank=True, max_length=200)),
                ('user', models.OneToOneField(blank=True, help_text='Người dùng tương ứng với hồ sơ.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile_set', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_book_name', models.CharField(help_text='Tên gợi nhớ của địa chỉ nhận hàng. Ví dụ: Địa chỉ 1, Địa chỉ 2,...', max_length=255, verbose_name='Tên địa chỉ')),
                ('first_name', models.CharField(help_text='Tên của người nhận hàng', max_length=255, verbose_name='Tên')),
                ('last_name', models.CharField(help_text='Họ của người nhận hàng', max_length=255, verbose_name='Họ')),
                ('email', models.EmailField(help_text='Địa chỉ Email của người nhận hàng', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(help_text='Số điện thoại của người nhận hàng', max_length=30, verbose_name='Số điện thoại')),
                ('street', models.CharField(help_text='Địa chỉ của người nhận hàng, gồm số nhà và tên đường,...', max_length=255, verbose_name='Địa chỉ cụ thể')),
                ('state', models.CharField(blank=True, help_text='Tên quận huyện người nhận hàng đang sống', max_length=255, null=True, verbose_name='Quận / Huyện')),
                ('city', models.CharField(blank=True, help_text='Tên thành phố, thị xã người nhận hàng đang sống', max_length=255, verbose_name='Thành Phố / Thị Xã')),
                ('country', models.CharField(help_text='Quốc gia người nhận hàng đang sống', verbose_name=django_countries.fields.CountryField(max_length=2))),
                ('zip_code', models.CharField(help_text='Mã bưu chính', max_length=10)),
                ('is_default', models.BooleanField(default=False, help_text='Trường đánh dấu địa chỉ mặc định của người dùng.', verbose_name='Địa chỉ mặc định')),
                ('admin_notes', models.TextField(blank=True, help_text='Ghi chú của quản trị viên.')),
                ('removed', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(blank=True, help_text='Hồ sơ người dùng', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_shippingaddress_set', to='profiles.profile', verbose_name='Hồ sơ')),
            ],
        ),
    ]
